#include "protocol.hpp"
#include "net.hpp"
#include <mbedtls/ctr_drbg.h>
#include <mbedtls/entropy.h>
#include <mbedtls/error.h>
#include <mbedtls/net_sockets.h>
#include <mbedtls/ssl.h>
#include <mbedtls/x509_crt.h>
#include <algorithm>
#include <cctype>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <sys/socket.h>
#include <sys/time.h>

namespace mail {
namespace {
class Stream {
    mbedtls_net_context net_{};mbedtls_ssl_context ssl_{};mbedtls_ssl_config conf_{};mbedtls_x509_crt ca_{};mbedtls_ctr_drbg_context rng_{};mbedtls_entropy_context entropy_{};
    bool connected_=false,tls_=false;std::string pending_;
    std::string tls_error(int rc){char buf[256];mbedtls_strerror(rc,buf,sizeof buf);return std::string(buf)+" ("+std::to_string(rc)+")";}
public:
    Stream(){mbedtls_net_init(&net_);mbedtls_ssl_init(&ssl_);mbedtls_ssl_config_init(&conf_);mbedtls_x509_crt_init(&ca_);mbedtls_ctr_drbg_init(&rng_);mbedtls_entropy_init(&entropy_);}
    ~Stream(){close();mbedtls_ssl_free(&ssl_);mbedtls_ssl_config_free(&conf_);mbedtls_x509_crt_free(&ca_);mbedtls_ctr_drbg_free(&rng_);mbedtls_entropy_free(&entropy_);}
    bool connect(const std::string&host,const std::string&port,bool implicit,std::string&err){char*end=nullptr;long port_number=std::strtol(port.c_str(),&end,10);if(host.empty()||host.size()>253||host.find_first_of("\r\n \t/\\")!=std::string::npos||port.empty()||!end||*end||port_number<1||port_number>65535){err="Invalid mail server address";return false;}int r=mbedtls_net_connect(&net_,host.c_str(),port.c_str(),MBEDTLS_NET_PROTO_TCP);if(r){err="Connect failed: "+tls_error(r);return false;}connected_=true;timeval tv{20,0};setsockopt(net_.fd,SOL_SOCKET,SO_RCVTIMEO,&tv,sizeof tv);setsockopt(net_.fd,SOL_SOCKET,SO_SNDTIMEO,&tv,sizeof tv);return !implicit||start_tls(host,err);}
    bool start_tls(const std::string&host,std::string&err){if(!connected_){err="Mail socket is not connected";return false;}const char*pers="C1Max-mail-client";int r=mbedtls_ctr_drbg_seed(&rng_,mbedtls_entropy_func,&entropy_,(const unsigned char*)pers,std::strlen(pers));if(r){err="TLS random seed: "+tls_error(r);return false;}auto cert=c1::root()+"/shared/ca-certificates.crt";r=mbedtls_x509_crt_parse_file(&ca_,cert.c_str());if(r<0){err="Could not load TLS root certificates: "+tls_error(r);return false;}r=mbedtls_ssl_config_defaults(&conf_,MBEDTLS_SSL_IS_CLIENT,MBEDTLS_SSL_TRANSPORT_STREAM,MBEDTLS_SSL_PRESET_DEFAULT);if(r){err="TLS setup: "+tls_error(r);return false;}mbedtls_ssl_conf_authmode(&conf_,MBEDTLS_SSL_VERIFY_REQUIRED);mbedtls_ssl_conf_ca_chain(&conf_,&ca_,nullptr);mbedtls_ssl_conf_rng(&conf_,mbedtls_ctr_drbg_random,&rng_);mbedtls_ssl_conf_min_version(&conf_,MBEDTLS_SSL_MAJOR_VERSION_3,MBEDTLS_SSL_MINOR_VERSION_3);r=mbedtls_ssl_setup(&ssl_,&conf_);if(r){err="TLS setup: "+tls_error(r);return false;}r=mbedtls_ssl_set_hostname(&ssl_,host.c_str());if(r){err="TLS server name: "+tls_error(r);return false;}mbedtls_ssl_set_bio(&ssl_,&net_,mbedtls_net_send,mbedtls_net_recv,nullptr);while((r=mbedtls_ssl_handshake(&ssl_))==MBEDTLS_ERR_SSL_WANT_READ||r==MBEDTLS_ERR_SSL_WANT_WRITE){}if(r){err="TLS handshake: "+tls_error(r);return false;}uint32_t flags=mbedtls_ssl_get_verify_result(&ssl_);if(flags){char verify[512];mbedtls_x509_crt_verify_info(verify,sizeof verify,"",flags);err=std::string("TLS certificate rejected: ")+verify;return false;}tls_=true;return true;}
    bool write_all(const std::string&s,std::string&err){size_t at=0;while(at<s.size()){int n=tls_?mbedtls_ssl_write(&ssl_,(const unsigned char*)s.data()+at,s.size()-at):mbedtls_net_send(&net_,(const unsigned char*)s.data()+at,s.size()-at);if(n==MBEDTLS_ERR_SSL_WANT_READ||n==MBEDTLS_ERR_SSL_WANT_WRITE)continue;if(n<=0){err="Mail connection write failed: "+tls_error(n);return false;}at+=n;}return true;}
    bool read_line(std::string&line,std::string&err){for(;;){auto pos=pending_.find('\n');if(pos!=std::string::npos){line=pending_.substr(0,pos);pending_.erase(0,pos+1);if(!line.empty()&&line.back()=='\r')line.pop_back();return true;}if(pending_.size()>65536){err="Mail server sent an oversized protocol line";return false;}unsigned char buf[4096];int n=tls_?mbedtls_ssl_read(&ssl_,buf,sizeof buf):mbedtls_net_recv(&net_,buf,sizeof buf);if(n==MBEDTLS_ERR_SSL_WANT_READ||n==MBEDTLS_ERR_SSL_WANT_WRITE)continue;if(n<=0){err="Mail connection read failed: "+tls_error(n);return false;}pending_.append((char*)buf,n);}}
    void close(){if(connected_){if(tls_)mbedtls_ssl_close_notify(&ssl_);mbedtls_net_free(&net_);connected_=tls_=false;pending_.clear();}}
    bool tls()const{return tls_;}
};
std::string trim(std::string s){auto a=s.find_first_not_of(" \t\r\n");if(a==std::string::npos)return {};return s.substr(a,s.find_last_not_of(" \t\r\n")-a+1);}
std::string b64(const std::string&s){static const char*t="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";std::string o;unsigned v=0,b=0;for(unsigned char c:s){v=(v<<8)|c;b+=8;while(b>=6){b-=6;o+=t[(v>>b)&63];}}if(b)o+=t[(v<<(6-b))&63];while(o.size()%4)o+='=';return o;}
std::string b64decode(const std::string&s){static const char*t="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";std::string o;unsigned v=0,b=0;for(unsigned char c:s){if(c=='='||std::isspace(c))continue;auto p=std::strchr(t,c);if(!p)continue;v=(v<<6)|unsigned(p-t);b+=6;if(b>=8){b-=8;o+=char((v>>b)&255);}}return o;}
bool status(Stream&s,std::string&line,std::string&err){if(!s.read_line(line,err))return false;if(line.size()<3||line[0]!='+') {if(err.empty())err="Mail server: "+line;return false;}return true;}
bool smtp_reply(Stream&s,int expected,std::string&err){std::string line;if(!s.read_line(line,err))return false;if(line.size()<3||!std::isdigit((unsigned char)line[0])){err="Invalid SMTP response: "+line;return false;}int code=std::atoi(line.c_str());bool more=line.size()>3&&line[3]=='-';while(more){if(!s.read_line(line,err))return false;more=line.size()>3&&line[3]=='-';}if(code!=expected){err="SMTP "+std::to_string(code)+": "+line;return false;}return true;}
bool pop_command(Stream&s,const std::string&cmd,std::string&err){return s.write_all(cmd+"\r\n",err);}
std::string safe_header(std::string s){s.erase(std::remove(s.begin(),s.end(),'\r'),s.end());s.erase(std::remove(s.begin(),s.end(),'\n'),s.end());return s;}
std::string decode_qp(std::string s){std::string o;for(size_t i=0;i<s.size();i++){if(s[i]=='='&&i+2<s.size()){if(s[i+1]=='\r'&&s[i+2]=='\n'){i+=2;continue;}auto hex=[](char c){if(c>='0'&&c<='9')return c-'0';if(c>='A'&&c<='F')return c-'A'+10;if(c>='a'&&c<='f')return c-'a'+10;return -1;};int a=hex(s[i+1]),b=hex(s[i+2]);if(a>=0&&b>=0){o+=char((a<<4)|b);i+=2;continue;}}o+=s[i];}return o;}
Message parse_message(unsigned number,const std::string&raw){Message m;m.number=number;auto split=raw.find("\r\n\r\n");size_t body_at=split==std::string::npos?std::string::npos:split+4;if(split==std::string::npos){split=raw.find("\n\n");if(split!=std::string::npos)body_at=split+2;}std::string hdr=raw.substr(0,split),body=body_at==std::string::npos?raw:raw.substr(body_at);size_t from=hdr.find("From:"),sub=hdr.find("Subject:");if(from!=std::string::npos){auto e=hdr.find('\n',from);m.from=trim(hdr.substr(from+5,e==std::string::npos?e:e-from-5));}if(sub!=std::string::npos){auto e=hdr.find('\n',sub);m.subject=trim(hdr.substr(sub+8,e==std::string::npos?e:e-sub-8));}auto transfer=hdr.find("Content-Transfer-Encoding:");if(transfer!=std::string::npos){auto e=hdr.find('\n',transfer);auto v=hdr.substr(transfer,e==std::string::npos?e:e-transfer);for(char&c:v)c=char(std::tolower((unsigned char)c));if(v.find("base64")!=std::string::npos)body=b64decode(body);else if(v.find("quoted-printable")!=std::string::npos)body=decode_qp(body);}auto mime=hdr.find("Content-Type:");if(mime!=std::string::npos){auto e=hdr.find('\n',mime);auto v=hdr.substr(mime,e==std::string::npos?e:e-mime);for(char&c:v)c=char(std::tolower((unsigned char)c));if(v.find("text/plain")==std::string::npos)body="(Message body is HTML or an unsupported MIME part. Headers are shown above.)\n\n"+body;}std::string normalized;normalized.reserve(body.size());for(size_t i=0;i<body.size();i++){if(body[i]=='\r'){if(i+1<body.size()&&body[i+1]=='\n')i++;normalized+='\n';}else normalized+=body[i];}m.body=normalized.substr(0,4096);return m;}
bool valid_address(const std::string&s){return !s.empty()&&s.find('@')!=std::string::npos&&s.find_first_of("\r\n <>")==std::string::npos;}
}

bool receive(const Config&c,std::vector<Message>&messages,std::string&error){messages.clear();if(c.username.empty()||c.password.empty()||c.pop_host.empty()){error="Set the POP3 server and account first";return false;}Stream s;bool implicit=c.pop_port=="995";if(!s.connect(c.pop_host,c.pop_port,implicit,error))return false;std::string line;if(!status(s,line,error)){s.close();return false;}if(!implicit){if(!pop_command(s,"STLS",error)||!status(s,line,error)){s.close();return false;}if(!s.start_tls(c.pop_host,error)){s.close();return false;}}if(!s.tls()){error="Refusing to send mailbox credentials without verified TLS";s.close();return false;}if(!pop_command(s,"USER "+safe_header(c.username),error)||!status(s,line,error)){s.close();return false;}if(!pop_command(s,"PASS "+safe_header(c.password),error)||!status(s,line,error)){s.close();return false;}if(!pop_command(s,"LIST",error)||!status(s,line,error)){s.close();return false;}std::vector<unsigned> ids;while(s.read_line(line,error)&&line!="."){unsigned id=0,size=0;if(std::sscanf(line.c_str(),"%u %u",&id,&size)==2){if(ids.size()==8)ids.erase(ids.begin());ids.push_back(id);}}if(!error.empty()){s.close();return false;}for(auto id:ids){if(!pop_command(s,"RETR "+std::to_string(id),error)||!status(s,line,error)){s.close();return false;}std::string raw;size_t total=0;while(s.read_line(line,error)&&line!="."){if(!line.empty()&&line[0]=='.')line.erase(0,1);if(total<262144){raw+=line+"\r\n";total+=line.size()+2;}}if(!error.empty()){s.close();return false;}messages.push_back(parse_message(id,raw));}pop_command(s,"QUIT",error);s.close();return true;}

bool send(const Config&c,const std::string&to,const std::string&subject,const std::string&body,std::string&error){if(c.username.empty()||c.password.empty()||c.smtp_host.empty()||!valid_address(to)){error="Set SMTP credentials and enter a valid recipient";return false;}std::string from=c.sender.empty()?c.username:c.sender;if(!valid_address(from)){error="Set a valid From address";return false;}Stream s;bool implicit=c.smtp_port=="465";if(!s.connect(c.smtp_host,c.smtp_port,implicit,error))return false;std::string line;if(!smtp_reply(s,220,error)){s.close();return false;}if(!implicit){if(!s.write_all("EHLO c1max.local\r\n",error)||!smtp_reply(s,250,error)||!s.write_all("STARTTLS\r\n",error)||!smtp_reply(s,220,error)||!s.start_tls(c.smtp_host,error)){s.close();return false;}if(!s.write_all("EHLO c1max.local\r\n",error)||!smtp_reply(s,250,error)){s.close();return false;}}if(!s.tls()){error="Refusing to send mailbox credentials without verified TLS";s.close();return false;}
    if(!s.write_all("AUTH LOGIN\r\n",error)||!smtp_reply(s,334,error)||!s.write_all(b64(c.username)+"\r\n",error)||!smtp_reply(s,334,error)||!s.write_all(b64(c.password)+"\r\n",error)||!smtp_reply(s,235,error)){s.close();return false;}
    if(!s.write_all("MAIL FROM:<"+from+">\r\n",error)||!smtp_reply(s,250,error)||!s.write_all("RCPT TO:<"+to+">\r\n",error)||!smtp_reply(s,250,error)||!s.write_all("DATA\r\n",error)||!smtp_reply(s,354,error)){s.close();return false;}
    std::string normalized;for(size_t i=0;i<body.size();i++){if(body[i]=='\r'){if(i+1<body.size()&&body[i+1]=='\n')i++;normalized+="\r\n";}else if(body[i]=='\n')normalized+="\r\n";else normalized+=body[i];}std::string stuffed;size_t at=0;while(at<normalized.size()){if(at==0||normalized[at-1]=='\n')if(normalized[at]=='.')stuffed+='.';stuffed+=normalized[at++];}if(stuffed.empty()||stuffed.substr(stuffed.size()>2?stuffed.size()-2:0)!="\r\n")stuffed+="\r\n";
    std::string msg="From: <"+from+">\r\nTo: <"+to+">\r\nSubject: =?UTF-8?B?"+b64(subject)+"?=\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Transfer-Encoding: 8bit\r\n\r\n"+stuffed+".\r\n";if(!s.write_all(msg,error)||!smtp_reply(s,250,error)||!s.write_all("QUIT\r\n",error)||!smtp_reply(s,221,error)){s.close();return false;}s.close();return true;}
}
