/* Original-device FFmpeg 4.2 decode tap. No encoder, framebuffer or audio I/O.
 * The exact upstream AVFrame header is vendored; only libavutil 56.31.100 is
 * accepted. Build with tools/build-yuv-pipe.sh (MIPS O32, FP64, NaN2008).
 */
#define _GNU_SOURCE
#include <dlfcn.h>
#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include "libavutil/frame.h"

/* These two types remain opaque; their layout is never accessed. */
struct AVCodecContext;
struct AVPacket;
typedef int (*decode_function)(struct AVCodecContext *, AVFrame *, int *, const struct AVPacket *);
typedef unsigned (*version_function)(void);
static int output_fd = -1, checked = 0, failed = 0, width = 0, height = 0;
static int aspect_n = 1, aspect_d = 1;
static decode_function original_decode;
static unsigned char packet[512 * 288 * 3 / 2 + 160];

static void fail(const char *reason)
{
    char line[96];
    int n;
    if (failed) return;
    failed = 1;
    if (output_fd >= 0) { close(output_fd); output_fd = -1; }
    n = snprintf(line, sizeof(line), "C1_YUV_ERROR=%s\n", reason);
    if (n > 0 && n < (int)sizeof(line)) (void)write(STDERR_FILENO, line, (size_t)n);
}

static int send_packet(const unsigned char *bytes, size_t size)
{
    sigset_t block, previous, pending;
    int had_pending = 0, result = 1, saved = 0;
    sigemptyset(&block); sigaddset(&block, SIGPIPE);
    if (sigprocmask(SIG_BLOCK, &block, &previous)) { fail("signal_mask"); return 0; }
    if (!sigpending(&pending)) had_pending = sigismember(&pending, SIGPIPE);
    while (size) {
        ssize_t count = write(output_fd, bytes, size);
        if (count > 0) { bytes += count; size -= (size_t)count; continue; }
        if (count < 0 && errno == EINTR) continue;
        saved = errno; result = 0; break;
    }
    /* Consume only the SIGPIPE generated by our failed write, preserving a
     * signal already pending on entry and the caller's original signal mask. */
    if (!result && saved == EPIPE && !had_pending) {
        struct timespec zero = {0, 0};
        while (sigtimedwait(&block, NULL, &zero) < 0 && errno == EINTR) {}
    }
    sigprocmask(SIG_SETMASK, &previous, NULL);
    if (!result) fail("write_fifo");
    return result;
}

static int start_output(const AVFrame *frame, const char *fifo)
{
    int flags, length;
    version_function version = (version_function)dlsym(RTLD_NEXT, "avutil_version");
    checked = 1;
    if (!version || version() != AV_VERSION_INT(56, 31, 100)) { fail("abi_mismatch"); return 0; }
    if (fifo[0] != '/') { fail("open_fifo"); return 0; }
    output_fd = open(fifo, O_WRONLY | O_NONBLOCK | O_CLOEXEC | O_NOFOLLOW);
    if (output_fd < 0) { fail("open_fifo"); return 0; }
    if (fcntl(output_fd, F_GETPIPE_SZ) < 0) { fail("not_fifo"); return 0; }
    flags = fcntl(output_fd, F_GETFL);
    if (flags < 0 || fcntl(output_fd, F_SETFL, flags & ~O_NONBLOCK) < 0) { fail("open_fifo"); return 0; }
    width = frame->width; height = frame->height;
    if (frame->sample_aspect_ratio.num > 0 && frame->sample_aspect_ratio.num <= 1000000 &&
        frame->sample_aspect_ratio.den > 0 && frame->sample_aspect_ratio.den <= 1000000) {
        aspect_n = frame->sample_aspect_ratio.num; aspect_d = frame->sample_aspect_ratio.den;
    }
    /* Server transcode contract: progressive planar 8-bit 4:2:0 at 20 fps.
     * Original MPlayer loop pacing is retained, but this hook runs BEFORE VO
     * presentation and can expose a frame early. Audio/video synchronization
     * requires separate authorized on-device audio testing; it is not proven
     * by the silent FIFO or decode tests. No extra frame delay is added here. */
    length = snprintf((char *)packet, sizeof(packet), "YUV4MPEG2 W%d H%d F20:1 Ip A%d:%d C420jpeg\n",
                      width, height, aspect_n, aspect_d);
    return length > 0 && length < 160 && send_packet(packet, (size_t)length);
}

static void emit_frame(const AVFrame *frame)
{
    const char *fifo = getenv("C1_YUV_FIFO");
    size_t used = 6;
    int plane, row;
    if (failed || !fifo || !*fifo) return;
    /* Check the library version BEFORE accessing any AVFrame member. */
    if (!checked) {
        version_function version = (version_function)dlsym(RTLD_NEXT, "avutil_version");
        if (!version || version() != AV_VERSION_INT(56, 31, 100)) { fail("abi_mismatch"); return; }
    }
    if (frame->format != AV_PIX_FMT_YUV420P) { fail("unsupported_format"); return; }
    if (frame->width < 2 || frame->height < 2 || frame->width > 512 || frame->height > 288 ||
        (frame->width & 1) || (frame->height & 1)) { fail("invalid_geometry"); return; }
    if (frame->interlaced_frame) { fail("interlaced"); return; }
    for (plane = 0; plane < 3; ++plane) {
        int w = plane ? frame->width / 2 : frame->width;
        int stride = frame->linesize[plane];
        if (!frame->data[plane] || stride < -32768 || stride > 32768 ||
            (stride >= 0 ? stride : -stride) < w) { fail("invalid_stride"); return; }
    }
    if (!checked && !start_output(frame, fifo)) return;
    if (frame->width != width || frame->height != height) { fail("geometry_changed"); return; }
    memcpy(packet, "FRAME\n", 6);
    for (plane = 0; plane < 3; ++plane) {
        int w = plane ? width / 2 : width;
        int h = plane ? height / 2 : height;
        for (row = 0; row < h; ++row) {
            memcpy(packet + used, frame->data[plane] + (ptrdiff_t)row * frame->linesize[plane], (size_t)w);
            used += (size_t)w;
        }
    }
    (void)send_packet(packet, used);
}

int avcodec_decode_video2(struct AVCodecContext *context, AVFrame *frame,
                         int *got_picture, const struct AVPacket *encoded)
{
    int result, decoder_errno;
    if (!original_decode)
        original_decode = (decode_function)dlsym(RTLD_NEXT, "avcodec_decode_video2");
    if (!original_decode) {
        if (got_picture) *got_picture = 0;
        fail("missing_decoder"); return -ENOSYS;
    }
    result = original_decode(context, frame, got_picture, encoded);
    decoder_errno = errno;
    if (result >= 0 && got_picture && *got_picture && frame) emit_frame(frame);
    errno = decoder_errno;
    return result;
}
