#include "reader.hpp"
#include <algorithm>
#include <cctype>
#include <cstdlib>

namespace crosspoint {
namespace {
std::string lower(std::string s){for(char &c:s)c=char(std::tolower((unsigned char)c));return s;}
void utf8(std::string &out,unsigned cp){if(cp<=0x7f)out+=char(cp);else if(cp<=0x7ff){out+=char(0xc0|(cp>>6));out+=char(0x80|(cp&63));}else if(cp<=0xffff){out+=char(0xe0|(cp>>12));out+=char(0x80|((cp>>6)&63));out+=char(0x80|(cp&63));}else{out+=char(0xf0|(cp>>18));out+=char(0x80|((cp>>12)&63));out+=char(0x80|((cp>>6)&63));out+=char(0x80|(cp&63));}}
std::string entities(const std::string &s){std::string out;out.reserve(s.size());for(size_t i=0;i<s.size();){if(s[i]!='&'){out+=s[i++];continue;}auto end=s.find(';',i+1);if(end==std::string::npos||end-i>12){out+=s[i++];continue;}auto e=s.substr(i+1,end-i-1);unsigned cp=0;bool ok=true;if(e=="amp")cp='&';else if(e=="lt")cp='<';else if(e=="gt")cp='>';else if(e=="quot")cp='"';else if(e=="apos"||e=="#39")cp='\'';else if(e.size()>1&&e[0]=='#'){char *p=nullptr;cp=std::strtoul(e.c_str()+((e.size()>2&&(e[1]=='x'||e[1]=='X'))?2:1),&p,(e.size()>2&&(e[1]=='x'||e[1]=='X'))?16:10);ok=p&&!*p&&cp<=0x10ffff;}else ok=false;if(ok)utf8(out,cp);else out.append(s,i,end-i+1);i=end+1;}return out;}
std::string strip_tag(const std::string &tag){auto name=lower(tag);auto p=name.find_first_not_of("< /\t\r\n");if(p==std::string::npos)return {};name=name.substr(p);auto e=name.find_first_of(" />\t\r\n");if(e!=std::string::npos)name.resize(e);static const char *blocks[]={"p","div","br","li","h1","h2","h3","h4","tr","section","article","blockquote","hr","title"};for(auto *b:blocks)if(name==b)return "\n";return {};}
}
std::string html_text(const std::string &html){std::string out;out.reserve(html.size());bool tag=false,space=false;std::string token;for(size_t i=0;i<html.size();){char c=html[i++];if(!tag&&c=='<'){tag=true;token.clear();continue;}if(tag){if(c=='>'){tag=false;auto name=lower(token);if(name.find("script")!=std::string::npos||name.find("style")!=std::string::npos){std::string end="</"+(name.find("script")!=std::string::npos?std::string("script"):std::string("style"))+">";auto rest=lower(html.substr(i));auto p=rest.find(end);if(p!=std::string::npos)i+=p+end.size();}auto br=strip_tag(token);if(!br.empty()){while(!out.empty()&&out.back()==' ')out.pop_back();if(out.empty()||out.back()!='\n')out+='\n';space=false;}}else if(token.size()<96)token+=c;continue;}if(c=='&'){auto semi=html.find(';',i);if(semi!=std::string::npos&&semi-i<12){auto decoded=entities(html.substr(i-1,semi-i+2));for(char d:decoded){if(std::isspace((unsigned char)d)){space=true;}else{if(space&&!out.empty()&&out.back()!='\n')out+=' ';out+=d;space=false;}}i=semi+1;continue;}}if(std::isspace((unsigned char)c)){space=true;continue;}if(space&&!out.empty()&&out.back()!='\n')out+=' ';out+=c;space=false;}while(!out.empty()&&(out.back()==' '||out.back()=='\n'))out.pop_back();return out;}

std::string markdown_text(const std::string &md){std::string out;out.reserve(md.size());bool line_start=true,code=false;for(size_t i=0;i<md.size();){char c=md[i++];if(c=='\n'){out+='\n';line_start=true;continue;}if(line_start&&c=='#'){while(i<md.size()&&md[i]=='#')i++;if(i<md.size()&&md[i]==' ')i++;out+='\n';line_start=false;continue;}line_start=false;if(c=='`'){code=!code;continue;}if(!code&&(c=='*'||c=='_'||c=='~'))continue;if(!code&&c=='['){auto mid=md.find("](",i),end=mid==std::string::npos?mid:md.find(')',mid+2);if(mid!=std::string::npos&&end!=std::string::npos){out.append(md,i,mid-i);i=end+1;continue;}}if(c=='>'&&out.empty())continue;out+=c;}return out;}

std::vector<std::string> pages(const std::string &text,size_t page_chars){std::vector<std::string> out;if(page_chars<100)page_chars=100;size_t start=0;while(start<text.size()){size_t i=start,count=0,last_break=start;while(i<text.size()&&count<page_chars){unsigned char c=text[i];size_t step=c<0x80?1:(c<0xe0?2:(c<0xf0?3:4));if(i+step>text.size())step=1;if(c=='\n'||c==' '||c=='\t')last_break=i+step;i+=step;count++;}if(i<text.size()&&last_break>start+page_chars/2)i=last_break;if(i<=start)i=std::min(text.size(),start+page_chars);out.push_back(text.substr(start,i-start));start=i;while(start<text.size()&&text[start]=='\n')start++;}if(out.empty())out.emplace_back();return out;}

}
